### ISSUE TITLE
Why the name @passy?

### ISSUE THREAD

**Issue by stephenplusplus** [passy/ama#1]

**Comment by passy** [comment]
That's a great question! (I'm gonna say that for every question to make the asker feel smart.)

The name is actually from the elementary school days. "Pascal" is obviously way too long and people in Germany really like putting "ee" sounds to the end of words to turn them into nicknames or just make them sound cuter. Pretty much all of my friends had some sort of nickname ending with an "ee" sound. However, using a "y" for that is rather unusual, which is exactly why I went with it.

An unfortunate consequence of that name is that it's very close to some not-so-nice words and some sites won't let me register it.
