### ISSUE TITLE
Why carrots?

### ISSUE THREAD

**Issue by sindresorhus** [passy/ama#13]

**Comment by passy** [comment]
What? Why?! Why not? What else? What are you even implying there? Anyway, good question.

Just some supporting facts:

![screen shot 2015-07-07 at 12 26 50](https://cloud.githubusercontent.com/assets/9906/8545156/94ebc178-24a3-11e5-90db-c8334cf8e22e.png)

![screen shot 2015-07-07 at 12 28 35](https://cloud.githubusercontent.com/assets/9906/8545168/b857b48c-24a3-11e5-9026-1b23a1fd3255.png)

![screen shot 2015-07-07 at 12 29 47](https://cloud.githubusercontent.com/assets/9906/8545191/e4106b00-24a3-11e5-8bdd-6bddb8c132d0.png)
