### ISSUE TITLE
What do you think about Rust?

### ISSUE THREAD

**Issue by sindresorhus** [passy/ama#14]
Especially compared to Haskell.

**Comment by robbbz** [comment]
:+1: Would love to see this answer.

**Comment by robbbz** [comment]
:+1: Would love to hear this answer.

**Comment by passy** [comment]
Beautiful question.

Programming languages are tools for me. And there are different tools for different jobs. Haskell and Rust are very different tools for very different jobs. Hence, you can't compare them in a fair way.

Rust fits in a niche that was previously unoccupied. There are low-level, unsafe languages like C/C++ and managed, high-level, safe languages like Python, Go, JavaScript, Haskell, etc. Rust is a safe and still low-level. It focuses on providing zero-cost abstractions, doesn't come with a garbage collector and yet provides memory safety. I'd like to have Rust in my toolbelt for when I need to drop down to that level. That said, I personally don't see a lot of use for it in my day-to-day work. Where I see Rust as being incredibly useful is for runtime systems and performance-critical infrastructure pieces. Browsers, rendering engines, game engines, code that runs space ships. I personally prefer having powerful abstractions and expressiveness over those features - most of the time. Haskell gives you incredible expressiveness and code reuse at the cost of operating at a way higher level.

In general, I'm way more excited about what other people do with Rust than what I can do with it. I hope that we'll see more of critical pieces like web servers, TLS libraries, font rendering etc. being rewritten in Rust to eliminate the 80+% of security-relevant programming errors that make the headlines. For most of my work, however, I'm more comfortable up here on my high hors... erm, abstraction layer.

**Comment by Qix-** [comment]
:+1: Perfect, sensible answer.
