### ISSUE TITLE
What do you do when you're not coding?

### ISSUE THREAD

**Issue by stephenplusplus** [passy/ama#2]

**Comment by passy** [comment]
Excellent question! (See, I'm gonna run with this.)

I'm still trying to figure this one out. Going to the gym is the other fix part of my daily routine. I recently bought a PS4 to stop myself from coding when I'm home from work and it works pretty well! On the weekends, there's also friends and family as an alternative to staring at code. London is also an amazing city for just walking or cycling around and discovering new places. But I still feel like I need to come up with something else.

**Comment by sindresorhus** [comment]
Try photography ;)
