### ISSUE TITLE
Do you often meet open-source people in person?

### ISSUE THREAD

**Issue by robbbz** [passy/ama#29]

**Comment by passy** [comment]
Strong question!

From the inner circle of people that I work with a lot I see @addyosmani most often, but every time there's a web-themed conference I see a lot of people I've somehow come across on GitHub. It's super fascinating to meet people in real life that you've talked to for years over Twitter, through GitHub issues, IRC or Hangouts.

Last year at Google I/O we had a (subset of the) Yeoman contributors dinner.
![1403582484017](https://cloud.githubusercontent.com/assets/9906/8509278/b27ee106-2292-11e5-9b32-9ea52f5d53cd.jpg)

The year before (can't believe it's already been so long!) @addyosmani, @sindresorhus and I took a day to explore Paris together. 
![img_20131202_123905](https://cloud.githubusercontent.com/assets/9906/8509279/e82969b6-2292-11e5-8f25-265ae9e82cb2.jpg)

If you go to a random tech Meetup here in London it's almost impossible to avoid meeting someone whose code you've used before to some degree or even worked with on the same project. But I definitely hope to meet even more people IRL in the future, in particular (but not limited to) @stephenplusplus (see stephenplusplus/ama#4).

**Comment by stephenplusplus** [comment]
We will someday, my friend!

Also, don't forget [I showed up to that yo lunch](https://twitter.com/stephenplusplus/status/482209043097071617).

![image](https://cloud.githubusercontent.com/assets/723048/8509300/35992bf6-226a-11e5-8f4d-d7c5317f98f7.jpg)

**Comment by passy** [comment]
@stephenplusplus Woops!

**Comment by robbbz** [comment]
Thanks for the picture. I recognize some people.
