### ISSUE TITLE
what podcasts are you listening to and why?

### ISSUE THREAD

**Issue by robbbz** [passy/ama#30]

**Comment by arthurvr** [comment]
Related: what podcast player are you using? I tried some and hate all of them.

**Comment by passy** [comment]
I want to go into a bit more detail later, but for now, here's a dump of my library [as OPML](http://opmlviewer.com/Viewer/?https://gist.githubusercontent.com/passy/43f7e55701d8acc3269d/raw/524dfd498beb851323e698c576589347942399c4/podcasts.opml).

I use [![](https://lh6.ggpht.com/KItvb_F5fVTvQg3hWNc4idE_QBDjWgu5yDseSbb9fguTbGJGRvMbLEHqAZp-eKCSDA=w32) PocketCasts](http://www.shiftyjelly.com/pocketcasts) and can highly recommend it, even though it only supports 3x playback speed. I listen to all podcasts at at least 2.5x, but for some of them I'd be comfortable with more than 3x.

**Comment by passy** [comment]
For a lot of the podcasts from that list, I only listen to episodes that have interesting guests, interesting segments I can skip to or cover an interesting topics. JS Jabber for example hasn't been as interesting to me recently, so I pick and choose.

For a few of them, I listen to every episode. Including:
- Cognicast
- Mostly Erlang
- Type Theory Podcast
- Haskell Cast
- Up Up Down Down
- TechZing
- Planet Money
- Freakonomics
- ADB
- Functional Geekery
