### ISSUE TITLE
Which conferences you will attend this year?

### ISSUE THREAD

**Issue by DanielMSchmidt** [passy/ama#35]
Bonus questions:
- Will you be at [dotJS](http://www.dotjs.io/) like me? 
- Which conferences are in your opinion definitely worth attending?
- Is there a pattern how you choose the talks you attend? 
  - The ones which will most likely influence your daily working life?
  - The ones which give you a broad overview what about what is going on?

**Comment by passy** [comment]
Oh wow, you're at dotJS? Haven't bought a ticket yet, but now I might. I'll reply in more detail in a bit. :)

**Comment by DanielMSchmidt** [comment]
This would be so awesome! 

![Yeah](http://tclhost.com/6v6A5Z9.gif)

**Comment by callumacrae** [comment]
I was considering going to dotJS!

Is this you?

![screen shot 2015-07-10 at 14 08 04](https://cloud.githubusercontent.com/assets/472830/8619241/2312abe0-270d-11e5-828d-eae9b2fd1a77.png)

**Comment by passy** [comment]
Oh wow, it is!

**Comment by stephenplusplus** [comment]
Is the internet just one big game of [Where's Passy?](https://twitter.com/passy/status/618744199106703360)

**Comment by callumacrae** [comment]
[Apparently!](https://twitter.com/passy/status/619842393932722176)

**Comment by passy** [comment]
Ooph, still no answer and the year is getting closer and closer to its end. The only one that I'll attend for sure is [Droidcon UK 2015](uk.droidcon.com/2015/). I may still go to DotJS, but I'll decide that short-termed depending on what other people will go.

Traveling always burns me out, so I'd much rather go to some more meetups and bigger events in London. :)
