### ISSUE TITLE
What's the most annoying part of FOSS for you?

### ISSUE THREAD

**Issue by hemanth** [passy/ama#38]

**Comment by passy** [comment]
Nice question!

As a very concrete thing: People not reading `CONTRIBUTING.md`.

In a more abstract way: People not realizing that their are always humans sitting on the receiving end. Totally not true for everyone. Most people I interact with are actually great, but there are some bad apples who think by opening a pull request or just an issue they are suddenly entitled to my attention. If someone opens a pull request they've spend 5 minutes on, ignoring all the style guides, not writing tests or documentation, ignoring the tooling in place to point out those issues and requiring me to spend at least 15 minutes to point out all their mistakes and linking them to the places where it's described, it's just unfair towards the maintainers. It's important to realize that behind every repo here on GitHub there are people.

**Comment by hemanth** [comment]
What a humble reply :smiley:!

> It's important to realize that behind every repo here on GitHub there are people.

^ noted.
