### ISSUE TITLE
What are you doing for your birthday?

### ISSUE THREAD

**Issue by stephenplusplus** [passy/ama#47]
I hope it involves tea, carrots, and a barbell.

**Comment by DanielMSchmidt** [comment]
By the way, happy birthday!

![Happy Birthday](http://media.giphy.com/media/4MGGaawSIPGko/giphy.gif)

**Comment by passy** [comment]
Thanks, guys! Great question!

My parents are in London this week, so I took the day off and we went flipped a coin last night whether to go to Oxford or Windsor. We ended up with the latter and visited the [Window Castle], which is the royal residence. Weather was awesome for a trip and the castle is pretty swell.

![img_20150721_131652](https://cloud.githubusercontent.com/assets/9906/8812079/e48fc0c2-2ff1-11e5-89c3-572af9c53e18.jpg)
![img_20150721_134640](https://cloud.githubusercontent.com/assets/9906/8812080/e494c478-2ff1-11e5-9654-f282c41831f2.jpg)
![img_20150721_135232](https://cloud.githubusercontent.com/assets/9906/8812081/e49c8726-2ff1-11e5-83e9-dfaf21a87c90.jpg)
