### ISSUE TITLE
What's your favorite thing about ES2015 classes?

### ISSUE THREAD

**Issue by sindresorhus** [passy/ama#49]
:trollface:

**Comment by passy** [comment]
Not at all trollish question. :baby_chick: 

I actually don't hate ES2015 classes. What I strongly dislike is `extends`. Encapsulating data is fine and so are constructors. Giving people the massive footgun that is inheritance will inevitably throw overall JS code quality back, but given how strong the FP movement is, it might be possible to recover from it.

So back to your question: formalized records and constructors are a good thing. It alleviates the pain of having to check for individual fields on objects a little. If we could now remove the `extends` keyword, I'd already stop complaining.

**Comment by sindresorhus** [comment]
Hah, I thought you hated it all. Then we're actually in agreement.
