### ISSUE TITLE
Do you even lift bro?

### ISSUE THREAD

**Issue by paulmillr** [passy/ama#5]
![screen shot 2015-07-02 at 8 26 17 pm](https://cloud.githubusercontent.com/assets/574696/8483311/9d7b3566-20f8-11e5-9999-f7446ad7206b.png)

**Comment by passy** [comment]
Fantastic question.

I only [liftM](http://haddock.stackage.org/lts-2.16/base-4.7.0.2/Control-Monad.html#v:liftM).
