### ISSUE TITLE
How does Twitter invest in/evolve on the web?

### ISSUE THREAD

**Issue by hasdavidc** [passy/ama#52]
I'm curious as to interesting things Twitter does on the web (experiments, technologies, workarounds to limitations) and how Twitter has invested in its web experience compared to other platforms like native iOS and Android.

I genuinely don't mean to be accusatory at all (in fact, I have a very high view of Twitter), but it seems like both Facebook and Google have been doing a lot of work with JS (regarding libraries and tooling), but it seems Twitter engineers have been mostly silent with the exception of releasing https://flightjs.github.io/ and occasionally speaking at front end conferences.

**Comment by passy** [comment]
Great question that I have a lot of opinions on. Unfortunately, I cannot answer it in this context. 
Sorry about that.

**Comment by hasdavidc** [comment]
Very understandable - if I can press (not that it's a big deal or anything), is there a different context in which you'd be willing to answer?
