### ISSUE TITLE
What's your favorite time pass, when waiting for a flight?

### ISSUE THREAD

**Issue by hemanth** [passy/ama#61]
Let me guess: Answering AMAs ;)?

If so, next to fav?

**Comment by passy** [comment]
Good question. You are right with the number one. :)
Assuming reasonably fast internet, GitHubbing and working on my projects is the second. If the connection is rubbish, I'll either go through my Pocket and read some of the longer reads I've skipped on the train or go through my eBooks library. Today, I've read some more pages of [SICP](https://github.com/sarabander/sicp) for our Twitter UK book club.

**Comment by hemanth** [comment]
👍👌
