### ISSUE TITLE
@__daithi or @phuu_ebooks?

### ISSUE THREAD

**Issue by monchote** [passy/ama#62]
Which one is your favourite?

**Comment by passy** [comment]
The former, [4sho](https://github.com/sindresorhus/slang-haven#4sho). While I love \@phuu_ebooks for what it is, it's sometimes just eerily similar to the original one. \@__daithi, however, has his own style and yet manages to capture the essence of what makes @daithiocrualaoich.

**Comment by monchote** [comment]
+2

**Comment by daithiocrualaoich** [comment]
Oh! You two... ❤ #BestTeamEver
