### ISSUE TITLE
What do you suggest to those wanting to go more "full stack" than basic HTML, CSS, JS?

### ISSUE THREAD

**Issue by igregson** [passy/ama#63]

**Comment by passy** [comment]
"Full Stack Development" is a lie. I do not believe that there are any developers who are truly full-stack. I've worked on web apps, native Android apps and distributed backend services including capacity planning and load testing. All with millions of requests or interactions per second. And yet I'm most certainly not a full-stack developer. I know enough to do damage to all of them and I think it's important to have a full picture to make informed decisions, but ultimately you will need to find your niche and focus on something narrower than "the full stack". It's simply too much to learn and understand in one lifetime.

If you want to expand your knowledge beyond basic HTML, CSS and JS, pick up a new programming language. Do this a few times a year. Don't fret too much about which one to pick up. You will learn a lot by simply looking at something unfamiliar. Get uncomfortable. If all you've been doing so far has happened in mostly imperative languages, check out Erlang, OCaml, Clojure or Haskell.

I personally don't care too much these days about building something that I can ship into production, I just want to maximize the learnings and go as far down the rabbit hole as it takes me, even if that means that I'll never finish anything. If that's not your cup of tea, go simple first. Find some tutorials for Django, Rails or check out all those new PaaS offerings like Firebase and Parse that allow you to just write some simple snippets to get your backend up and running.

Don't believe the "Full-Stack" lie. You don't have to know everything to be a good developer or find a nice job. Follow your interests and build cool stuff.
