### ISSUE TITLE
How was your weekend?

### ISSUE THREAD

**Issue by robbbz** [passy/ama#68]

**Comment by passy** [comment]
Love that question!

Really good, thanks. Found some time to actually write some code, something that I felt like I didn't do much of during the last week or weekend. I also watched The Martian with some friends and thoroughly enjoyed it. Explored some more coffee shops in the area and found out that the one right on the other side of the road has a better internet connection than I have in my flat. Unfortunately, they close at 20.00 on a Sunday. There should be something like an AirBnB for late-night coffee shops with good WiFi.
