### ISSUE TITLE
What skill would you like to have?

### ISSUE THREAD

**Issue by robbbz** [passy/ama#75]

**Comment by passy** [comment]
Love that question!

Obviously there are the obvious skills probably most people would like to have among which invisibility and flying are, but unfortunately not being Elon Musk I consider my chances for obtaining those rather slim.

A skill I want to have that seems achievable is being a good public speaker. Right now I'm most definitely not one, but it seems to be mostly a matter of practice and putting yourself out there. I want to do more of this in 2016 and give some smaller talks at meetups and perhaps tackle something bigger at a conference. Let's see.
