### ISSUE TITLE
What do you think about Conventional Commits?

### ISSUE THREAD

**Issue by gepgecici** [passy/ama#82]
I have been using Conventional Commits for a while and I'm enjoying it for now. It provides me really good commit history, the only problem I have experience is I sometimes cannot find the best type with scope value.

As far as I can tell, you don't adapt it. Is there a reason for that? or do you plan to adapt anytime soon?

**Comment by passy** [comment]
I hadn't seen this but I really like the idea. I've been a fan of the Angular convention which this appears to be based on. The problem with all of these conventions is that you need to get buy-in from your team and if you work in a larger organisation or perhaps operate in a mono-repo, this gets even harder.

However, linters can help and with a well formulated and documented standard like this one it seems much easier to enforce than informal rules like "please use the imperative form for the top line and mention breaking changes".

Thanks for raising this. :)
